<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.22" />
    
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.22" />
    
    <PackageReference Include="Microsoft.Extensions.Identity.Stores" Version="10.0.1" />
    
    <PackageReference Include="NetArchTest.Rules" Version="1.3.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Claims\Events\" />
    <Folder Include="Claims\ValueObjects\" />
    <Folder Include="Claims\Rules\" />
    <Folder Include="Driver\Enums\" />
    <Folder Include="Driver\ValueObjects\" />
    <Folder Include="Inventory\ValueObjects\" />
    <Folder Include="Invoices\Enums\" />
    <Folder Include="Notifications\Events\" />
    <Folder Include="Notifications\Rules\" />
    <Folder Include="Payments\Events\" />
    <Folder Include="Payments\Rules\" />
    <Folder Include="Roles\Events\" />
    <Folder Include="Roles\Rules\" />
    <Folder Include="Roles\ValueObjects\" />
    <Folder Include="Users\ValueObjects\" />
    <Folder Include="Vehicles\ValueObjects\" />
  </ItemGroup>

</Project>

